[WINDUP-3240] - Windup Technology Reports - Introduce new tiers in preparation for the new technology tags
windup/windup pull request #1443
Opened 2022-01-11 13:43 UTC by carlosthe19916

https://issues.redhat.com/browse/WINDUP-3240

2022-01-26 13:04 UTC, PhilipCattanach commented
@carlosthe19916 Hi Carlos, I've been doing some testing and the Connect, Streaming tier seems to be missing.
Thanks,
Phil

2022-01-27 14:34 UTC, m-brophy requested changes

2022-01-27 14:34 UTC, m-brophy commented on reporting/impl/src/main/resources/org/jboss/windup/reporting/rules/generation/techreport/techReport-hierarchy.tags.xml
> +            <tag pseudo="true" name="place:Resource Management" title="Observability" parents="techBox:resource-management"/>
title incorrect

```suggestion
            <tag pseudo="true" name="place:Resource Management" title="Resource Management" parents="techBox:resource-management"/>
```

2022-01-27 14:34 UTC, m-brophy commented on reporting/impl/src/main/resources/org/jboss/windup/reporting/rules/generation/techreport/techReport-hierarchy.tags.xml
> +            <tag pseudo="true" name="place:Configuration Management" title="Observability" parents="techBox:configuration-management"/>
title incorrect

```suggestion
            <tag pseudo="true" name="place:Configuration Management" title="Configuration Management" parents="techBox:configuration-management"/>
```

2022-01-28 10:41 UTC, m-brophy approved these changes

2022-01-28 15:39 UTC, merged