Be able to skip not readable entries in a Zip Stream
windup/windup pull request #1482
Opened 2022-04-21 11:40 UTC by carlosthe19916

2022-04-21 12:39 UTC, jmle requested changes

2022-04-21 12:39 UTC, jmle commented on utils/src/main/java/org/jboss/windup/util/ZipUtil.java
> +    public static ZipEntry getNextEntry(ZipInputStream zis) throws IOException {
Does this method have to be public?

2022-04-21 12:39 UTC, jmle commented on utils/src/main/java/org/jboss/windup/util/ZipUtil.java
> +     * Return the next Entry of a ZipInputStream. If the nextEntry can not be read then kip it and continue with the next one
Typo in "kip"

2022-04-21 12:46 UTC, carlosthe19916 commented on utils/src/main/java/org/jboss/windup/util/ZipUtil.java
> +    public static ZipEntry getNextEntry(ZipInputStream zis) throws IOException {
Changed to private

2022-04-21 12:46 UTC, carlosthe19916 commented on utils/src/main/java/org/jboss/windup/util/ZipUtil.java
> +     * Return the next Entry of a ZipInputStream. If the nextEntry can not be read then kip it and continue with the next one
Thanks. Fixed and now it says "skip"

2022-12-15 08:55 UTC, jmle commented
@carlosthe19916 there are conflicts in this branch - I'd recommend to fix them before it gets stale, and maybe we can merge it

2022-12-19 10:24 UTC, jmle approved these changes

2022-12-19 10:24 UTC, merged