WINDUP-4219 update joox dependency
windup/windup pull request #1754
Opened 2024-08-17 14:40 UTC by GeorgeCattanach

updated org.jooq joox dependency to version 1.6.2

2024-08-19 09:35 UTC, PhilipCattanach submitted a review, later dismissed
LGTM

2024-08-19 12:41 UTC, m-brophy requested changes
There are 5 instances of this dependency in windup sub-projects, see here:
![image](https://github.com/user-attachments/assets/aed23fba-dea4-4109-aff4-0a2f1baeb58c)

We should really upgrade them all

2024-08-20 11:46 UTC, m-brophy approved these changes

2024-08-20 11:47 UTC, m-brophy commented
Thanks George, well done!

2024-08-20 11:47 UTC, merged